commands:
  enabled: true
  prefix: '>'
  channels: ['1229769887056920597']
  overrides:
    - name: 'ban'
      roles: ['1294920539093205064', '1304051473113677825', '1297079312016605225', '1305861251674542232', '1294920757633355887', '1294920926088921153', '1294920974591852554']

    - name: 'remove-punishment'
      roles: ['1294920539093205064', '1304051473113677825', '1297079312016605225', '1305861251674542232', '1294920757633355887']

punishments:
  editors: ['1294920539093205064', '1304051473113677825', '1297079312016605225', '1305861251674542232', '1294920757633355887', '1294920926088921153',]
  managers: ['1294920539093205064', '1304051473113677825', '1297079312016605225', '1305861251674542232', '1294920757633355887']

  defaultWarnDuration: 2592000000 # 1 month
  defaultMuteDuration: 21600000 # 6 hours

  additionalInfo:
    warn: 'If you feel like this punishment is unjustified, you may appeal it by creating a ticket or messaging a Lead Mod or above.'
    mute: 'If you feel like this punishment is unjustified, you may appeal it by filling out this form: https://forms.gle/Z5JLWes9DJmz9WdH8'
    kick: 'If you feel like this punishment is unjustified, you may appeal it by creating a ticket or messaging a Lead Mod or above.'
    ban: 'If you feel like this punishment is unjustified, you may appeal it by filling out this form: https://forms.gle/Z5JLWes9DJmz9WdH8'

lock:
  channels: ['1294918129238937620', '1294918145122893854', '1294918183148453948', '1294918194833915975', '1294920390174310440', '1294918609289609216', '1294918650020630579', '1294920437427474494', '1294920459552292864']
  overrides: 377960303168 # Will deny Send Messages, Send Messages In Threads, Create Public/Private Threads, Attach Files, Add Reactions, Connect (vc), Speak (vc), Video (vc)

tags:
  - name: '1'
    aliases: ['respect', 'toxic']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "💞 Be respectful."
          value: "Hate speech, toxicity and/or harassment is strictly prohibited. Treat others they way you would like to be treated."
          inline: false
  - name: '2'
    aliases: ['mature', 'maturity']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "🌴 Act mature."
          value: "We want to create a community that is mature and productive with how they use the server. While you can have fun, please remember the nature and purpose of the server."
          inline: false
  - name: '3'
    aliases: ['sfw', 'nsfw']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "💭 Keep the chat safe & appropriate.."
          value: "Use your common sense and don't find loopholes. Spam, drama, fighting, advertising and NSFW is strictly prohibited. "
          inline: false
  - name: 'mod'
    aliases: ['apply', 'staff']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "How do I apply for staff?"
          value: "To become a staff member, you must apply through our staff application. This form is available in <#1233676044070944810> when we require more staff, and you'll usually require around Level 25+ and 3 or less warnings to apply (but this may change)."
          inline: false
  - name: 'ranks'
    aliases: ['English', 'language']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "🔤 Keep it English."
          value: "Our team is only capable of moderating messages in the English language. Please keep all conversations in English."
          inline: false

reports:
  user: # User Reports
    enabled: true # A boolean (true/false)
    channelId: '1294919791039086602' # The channel in which message reports will be logged
    excluded: ['1294921829303189514'] # An array of role ids immune to message reports
    blacklist: [] # An array of role ids blacklisted from creating message report

  message: # Message Reports
    enabled: true # A boolean (true/false)
    channelId: '1294919791039086602' # The channel in which message reports will be logged
    excluded: ['1294921829303189514'] # An array of role ids immune to message reports
    blacklist: [] # An array of role ids blacklisted from creating message report
          
automod:
  filters:
    - name: 'No Swear Filter'
      enabled: false
      immuneRoles: ['1294921829303189514']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      customInfo: 'We are a SFW server, please do not use swear words.'
      fallbackResponse: 'Please do not send prohibited words!'
      content: ['word1', 'word2', 'word3']

    - name: 'No Slur Filter'
      enabled: false
      immuneRoles: ['1294921829303189514']
      immuneChannels: []
      punishment: 'Ban'
      customInfo: 'We are a welcoming and inclusive community, as such we will not tolerate any slurs.'
      fallbackResponse: "Slurs aren't welcome here buddy. Goodbye."
      content: ['slur1', 'slur2', 'slur3']

  links:
    - name: 'All Links Filter'
      enabled: true
      immuneRoles: ['1294921829303189514']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      customInfo: 'You are not allowed to send any links as they may contain malicious content.'
      fallbackResponse: 'Hi! Please do not send links, thanks!'
      whitelist: ['discord.com', 'discordapp.com', 'tenor.com'] # We whitelist the domain in the global filter but not in the tenor filter that gets triggered for users without any of the immune roles.

    - name: 'Tenor Links Filter'
      enabled: true
      immuneRoles: ['1294921829303189514', '1319177836933677098', '1297079860312801312',]
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      fallbackResponse: 'Hi! You cannot send tenor links yet as you are lacking an immune role to the tenor links filter!'
      whitelist: []

  mentions:
    - name: 'Owner Mention Filter'
      enabled: true
      immuneRoles: ['1294921829303189514']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      fallbackResponse: 'Hi! You cannot ping the owners as they are busy and will not respond to your message.'
      list: ['1291990791752912977']

    - name: 'Developer Mention Filter'
      enabled: false
      immuneRoles: ['1294921829303189514']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      fallbackResponse: 'Hi! You cannot ping the developers as they are busy and will not respond to your message.'
      list: ['1005206283596611614']

  antiSpam:
    maxMentions:
      enabled: true
      immuneRoles: ['1294921829303189514']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      limit: 5

    maxCharacters:
      enabled: true
      immuneRoles: ['1294921829303189514']     
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      limit: 400

    maxAttachments:
      enabled: true
      immuneRoles: ['1294921829303189514']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      limit: 8

logging:
  punishments:
    enabled: true
    channelId: '1294919805060517918'
  punishmentEdit:
    enabled: true
    channelId: '1294919805060517918'
  messages:
    enabled: true
    channelId: '1294919819468079176'
    excluded: ['']
  commands:
    enabled: false
    channelId: '1294919985264590888'
  mediaConversion:
    enabled: false
    channelIds: '1294919819468079176'
    logChannelId: '1294919819468079176' 
